config/routes.rb
Messaging::Application.routes.draw do
  get "book_of_entry/index"

  resources :journals

  resources :accounts

  resources :expenses

  resources :assert_accounts

  get "sendbox/index"
  get "sendbox/destroy"
  match "sendbox/:id", :to => "sendbox#show"

  get "inbox/index"

  get "inbox/show"
  match "inbox/:id", :to => "inbox#show"
  match "inbox", :to => "inbox#index"

  get "inbox/destroy"

  resources :messages

  get "home/index"

  devise_for :users

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/assert_account.rb
class AssertAccount < ActiveRecord::Base
  validate :presence, :name
end

app/controllers/assert_accounts_controller.rb
class AssertAccountsController < ApplicationController
  # GET /assert_accounts
  # GET /assert_accounts.xml
  def index
    @assert_accounts = AssertAccount.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @assert_accounts }
    end
  end

  # GET /assert_accounts/1
  # GET /assert_accounts/1.xml
  def show
    @assert_account = AssertAccount.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @assert_account }
    end
  end

  # GET /assert_accounts/new
  # GET /assert_accounts/new.xml
  def new
    @assert_account = AssertAccount.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @assert_account }
    end
  end

  # GET /assert_accounts/1/edit
  def edit
    @assert_account = AssertAccount.find(params[:id])
  end

  # POST /assert_accounts
  # POST /assert_accounts.xml
  def create
    @assert_account = AssertAccount.new(params[:assert_account])

    respond_to do |format|
      if @assert_account.save
        format.html { redirect_to(@assert_account, :notice => 'Assert account was successfully created.') }
        format.xml  { render :xml => @assert_account, :status => :created, :location => @assert_account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @assert_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /assert_accounts/1
  # PUT /assert_accounts/1.xml
  def update
    @assert_account = AssertAccount.find(params[:id])

    respond_to do |format|
      if @assert_account.update_attributes(params[:assert_account])
        format.html { redirect_to(@assert_account, :notice => 'Assert account was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @assert_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assert_accounts/1
  # DELETE /assert_accounts/1.xml
  def destroy
    @assert_account = AssertAccount.find(params[:id])
    @assert_account.destroy

    respond_to do |format|
      format.html { redirect_to(assert_accounts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/assert_accounts_helper.rb
module AssertAccountsHelper
end

app/views/assert_accounts/_form.html.haml
= semantic_form_for @assert_account do |f|
  = f.inputs do
    = f.input :name 
  = f.buttons

app/views/assert_accounts/edit.html.haml
%h1 Editing assert_account

= render 'form'

= link_to 'Show', @assert_account
\|
= link_to 'Back', assert_accounts_path

app/views/assert_accounts/index.html.haml
%h1 Listing assert_accounts

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @assert_accounts.each do |assert_account|
    %tr
      %td= assert_account.name
      %td= link_to 'Show', assert_account
      %td= link_to 'Edit', edit_assert_account_path(assert_account)
      %td= link_to 'Destroy', assert_account, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Assert account', new_assert_account_path

app/views/assert_accounts/new.html.haml
%h1 New assert_account

= render 'form'

= link_to 'Back', assert_accounts_path

app/views/assert_accounts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @assert_account.name

= link_to 'Edit', edit_assert_account_path(@assert_account)
\|
= link_to 'Back', assert_accounts_path