config/routes.rb
Messaging::Application.routes.draw do
  get "book_of_entry/index"

  resources :journals

  resources :accounts

  resources :expenses

  resources :assert_accounts

  get "sendbox/index"
  get "sendbox/destroy"
  match "sendbox/:id", :to => "sendbox#show"

  get "inbox/index"

  get "inbox/show"
  match "inbox/:id", :to => "inbox#show"
  match "inbox", :to => "inbox#index"

  get "inbox/destroy"

  resources :messages

  get "home/index"

  devise_for :users

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  after_create :edit_account_type_balance
  
  belongs_to :account
  
  def edit_account_type_balance
#######    if self.from == "1"
#######      credit
#######      debit
#######      cred.save!
#######    end
#######  end
#######  
#######  def credit
#######    cred = Account.find_by_account_type("assert")
#######    cred.balance = (cred.balance - self.amount)
#######  end
#######  
#######  def debit
#######    if self.to == "2"
#######      deb = Account.find_by_account_type("expense")
#######      deb.balance = (deb.balance + self.amount)
#######      deb.save!
    #######    end

    credit(self.from)
    debit(self.to)
  end


  ## This is my another way of working style Above is the old and that
    ## is working
    
#    get_the_string_and_value(self.from, self.to)

  def credit(val1)
    cred = Account.find(val1.to_i)
    cred.update_attributes(:balance => cred.balance - self.amount)
    cred.save!
  end
  def debit(val2)
    debt = Account.find(val2.to_i)
    debt.update_attributes(:balance => debt.balance + self.amount)
  end
  def get_the_string_and_value(val1, val2)
    @credit_bal = Account.find(val1.to_i).balance
    @debit_bal = Account.find(val2.to_i).balance
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  # GET /journals
  # GET /journals.xml
  def index
    @journals = Journal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @journals }
    end
  end

  # GET /journals/1
  # GET /journals/1.xml
  def show
    @journal = Journal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @journal }
    end
  end

  # GET /journals/new
  # GET /journals/new.xml
  def new
    @journal = Journal.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @journal }
    end
  end

  # GET /journals/1/edit
  def edit
    @journal = Journal.find(params[:id])
  end

  # POST /journals
  # POST /journals.xml
  def create
    @journal = Journal.new(params[:journal])

    respond_to do |format|
      if @journal.save
        format.html { redirect_to(@journal, :notice => 'Journal was successfully created.') }
        format.xml  { render :xml => @journal, :status => :created, :location => @journal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @journal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /journals/1
  # PUT /journals/1.xml
  def update
    @journal = Journal.find(params[:id])

    respond_to do |format|
      if @journal.update_attributes(params[:journal])
        format.html { redirect_to(@journal, :notice => 'Journal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @journal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.xml
  def destroy
    @journal = Journal.find(params[:id])
    @journal.destroy

    respond_to do |format|
      format.html { redirect_to(journals_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.haml
= semantic_form_for @journal do |f|
  = f.inputs do
    = f.input :from, :as => :select, :collection =>  Account.all
    = f.input :to, :as => :select, :collection =>  Account.all
    = f.input :description
    = f.input :amount
    = f.input :date
  = f.buttons

app/views/journals/edit.html.haml
%h1 Editing journal

= render 'form'

= link_to 'Show', @journal
\|
= link_to 'Back', journals_path

app/views/journals/index.html.haml
%h1 Listing journals

%table
  %tr
    %th From
    %th To
    %th Description
    %th Amount
    %th Date
    %th
    %th
    %th

  - @journals.each do |journal|
    %tr
      %td= journal.from
      %td= journal.to
      %td= journal.description
      %td= journal.amount
      %td= journal.date
      %td= link_to 'Show', journal
      %td= link_to 'Edit', edit_journal_path(journal)
      %td= link_to 'Destroy', journal, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Journal', new_journal_path

app/views/journals/new.html.haml
%h1 New journal

= render 'form'

= link_to 'Back', journals_path

app/views/journals/show.html.haml
%p#notice= notice

%p
  %b From:
  = @journal.from
%p
  %b To:
  = @journal.to
%p
  %b Description:
  = @journal.description
%p
  %b Amount:
  = @journal.amount
%p
  %b Date:
  = @journal.date

= link_to 'Edit', edit_journal_path(@journal)
\|
= link_to 'Back', journals_path